### ISSUE TITLE
Times out?

### ISSUE THREAD

**Issue by N01Important** [TheBrenny/sans-video-ripper#2]
Hello,

Thank you for making this. However I think the main.js has been updated and I'm not sure what needs to be done to see if it can be fixed.

```commandline
Setting up requires...
Collecting args...
Setting up consts...
Starting browser...
Going to: https://ondemand-player.sans.org/<course>...
Detected login page...
? Username: <username>
? Password:  [hidden]
Submitting...
Going back to: https://ondemand-player.sans.org/<course>...
/home/cstreb/node_modules/puppeteer-core/lib/cjs/puppeteer/util/Deferred.js:59
            this.#timeoutError = new Errors_js_1.TimeoutError(opts.message);
                                 ^

TimeoutError: Navigation timeout of 120000 ms exceeded
    at new Deferred (/home/<snip>/node_modules/puppeteer-core/lib/cjs/puppeteer/util/Deferred.js:59:34)
    at Deferred.create (/home/<snip>/node_modules/puppeteer-core/lib/cjs/puppeteer/util/Deferred.js:21:16)
    at new LifecycleWatcher (/home/<snip>/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/LifecycleWatcher.js:69:60)
    at CdpFrame.goto (/home/<snip>/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/Frame.js:151:29)
    at CdpFrame.<anonymous> (/home/<snip>/node_modules/puppeteer-core/lib/cjs/puppeteer/util/decorators.js:98:27)
    at CdpPage.goto (/home/<snip>/node_modules/puppeteer-core/lib/cjs/puppeteer/api/Page.js:588:43)
    at /home/<snip>/node_modules/sans-video-ripper/index.js:181:16
```

EDIT - when running with -H the browser will just sit and spin after the user auth process.

Test system is Ubuntu 22.04 using chromium

however I have similar issues on a M3 Mac and a Win11 laptop.

Any idea what next steps would look like?

**Comment by TheBrenny** [comment]
Sorry for the delay, should be fixed with the latest version

**Comment by TheBrenny** [comment]
Sorry for the delay, should be fixed with the latest version
